apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Chan's HomeLab
    theme: dark
    color: slate

    headerStyle: clean

    layout:
      Kubernetes:
        style: row
        columns: 3

      Monitoring:
        style: row
        columns: 2

      Network:
        style: row
        columns: 2
