apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-services
  namespace: homepage
data:
  services.yaml: |
    - Kubernetes:
        - Argo CD:
            href: https://argocd.home
            description: GitOps deployments

        - Grafana:
            href: http://grafana.home
            description: Metrics and logs

        - Longhorn:
            href: http://longhorn.home
            description: Kubernetes storage
        - Paperless-ngx:
            icon: paperless-ngx.png
            href: http://paperless.home
            description: Document management and OCR
        - Headlamp:
            href: http://headlamp.home
            description: Kubernetes dashboard

        - Uptime Kuma:
            href: http://kuma.home
            description: Service monitoring

        - Pi-hole:
            icon: pi-hole.png
            href: http://192.168.68.97/admin
            description: DNS filtering and local DNS
            widget:
              type: pihole
              url: http://192.168.68.97
              version: 6
              key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
              fields:
                - queries
                - blocked
                - blocked_percent
                - gravity
