- Kubernetes:
    - Argo CD:
        icon: argo-cd.png
        href: https://argocd.home
        description: GitOps and app deployments

    - Headlamp:
        icon: kubernetes.png
        href: http://headlamp.home
        description: Kubernetes cluster dashboard

    - Longhorn:
        icon: longhorn.png
        href: http://longhorn.home
        description: Persistent storage and volumes

     - Paperless-ngx:
        icon: paperless-ngx.png
        href: http://paperless.home
        description: Document management and OCR
- Monitoring:
    - Grafana:
        icon: grafana.png
        href: http://grafana.home
        description: Metrics, dashboards, and logs

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://kuma.home
        description: Service uptime monitoring

    - Pi-hole:
        icon: pi-hole.png
        href: http://192.168.68.97/admin
        description: DNS filtering and local DNS
        widget:
          type: pihole
          url: http://192.168.68.97
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
          fields:
            - queries
            - blocked
            - blocked_percent
            - gravity
