apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - longhorn-single.yaml
  - storage.yaml
  - postgres.yaml
  - valkey.yaml
  - paperless.yaml
  - service.yaml
  - ingress.yaml
